### ISSUE TITLE
Pycharm locks up

### ISSUE THREAD

**Issue by macfire** [raydac/netbeans-mmd-plugin#101]
Pycharm app locks up when trying to access "Edit" in Pycharm's main menu AFTER accessing "Add a file" to a mind map node.

Using IDEA Mind Map 1.5.1

**Comment by raydac** [comment]
I can't reproduce the issue under linux version of PyCharm, but looks like that can reproduce under Windows version
```
java.lang.IllegalArgumentException: button doesn't exist 0
              at java.desktop/java.awt.event.InputEvent.getMaskForButton(InputEvent.java:273)
              at java.desktop/java.awt.LightweightDispatcher.isMouseGrab(Container.java:4508)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:519)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:519)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:584)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6663)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
              at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:519)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:584)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6663)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
              at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupImpl$3(Utils.java:211)
              at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:595)
              at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:204)
              at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:294)
              at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:633)
              at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:293)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
              at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
              at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
              at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Handler.mousePressed(BasicMenuUI.java:519)
              at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
              at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
              at com.intellij.openapi.actionSystem.impl.ActionMenu.processMouseEvent(ActionMenu.java:264)
              at java.desktop/java.awt.Component.processEvent(Component.java:6419)
              at java.desktop/java.awt.Container.processEvent(Container.java:2263)
              at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
              at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
              at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
              at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
              at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
              at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
              at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
              at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
              at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
              at java.base/java.security.AccessController.doPrivileged(Native Method)
              at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
              at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
              at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
              at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
              at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
              at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
              at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
              at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
              at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
              at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
              at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
              at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
              at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
              at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
              at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
