### ISSUE TITLE
IJ: java.lang.IllegalStateException: Clipboard is busy

### ISSUE THREAD

**Issue by raydac** [raydac/netbeans-mmd-plugin#43]
```
update failed for AnAction(com.intellij.ide.actions.PasteAction) with ID=$Paste: Clipboard is busy

java.lang.IllegalStateException: Clipboard is busy
                at sun.awt.windows.WClipboard.openClipboard(Native Method)
                at sun.awt.datatransfer.SunClipboard.getClipboardFormatsOpenClose(SunClipboard.java:327)
                at sun.awt.datatransfer.SunClipboard.isDataFlavorAvailable(SunClipboard.java:188)
                at com.igormaznitsa.ideamindmap.editor.MindMapDocumentEditor.isPasteEnabled(MindMapDocumentEditor.java:879)
                at com.igormaznitsa.ideamindmap.editor.MindMapDocumentEditor.isPastePossible(MindMapDocumentEditor.java:872)
                at com.intellij.ide.actions.PasteAction.update(PasteAction.java:32)
                at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
                at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:257)
                at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
                at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:1005)
                at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:63)
                at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:182)
                at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
                at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:643)
                at com.intellij.openapi.wm.impl.FocusManagerImpl.h(FocusManagerImpl.java:624)
                at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:594)
                at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:476)
                at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2767)
                at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
                at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
                at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
                at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
                at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1406)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1396)
                at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1380)
                at javax.swing.Timer.fireActionPerformed(Timer.java:313)
                at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
                at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
                at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
                at java.awt.EventQueue.access$500(EventQueue.java:98)
                at java.awt.EventQueue$3.run(EventQueue.java:715)
                at java.awt.EventQueue$3.run(EventQueue.java:709)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
                at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
                at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
                at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ShirleyLuoppx** [comment]
so  how do u deal with this problem"java.lang.IllegalStateException: Clipboard is busy
"

**Comment by raydac** [comment]
it was fixed in last release

**Comment by Amankesarwani2202** [comment]
Same error is coming .Please tell how to resolve it !!

**Comment by raydac** [comment]
@Amankesarwani2202 which OS, which version and what are you doing to get such error?

**Comment by Amankesarwani2202** [comment]
Thank you !! But today morning I resolve it by going >>project structure >> sdk >>API .
