### ISSUE TITLE
Exception with IDEA 2019.1

### ISSUE THREAD

**Issue by SergeyMalenkov** [raydac/netbeans-mmd-plugin#50]
The following exception show that KnowledgeViewPane creates inconsistent SelectInTarget.
This may lead to issues with ScrollTo actions.

java.lang.Throwable: Unexpected SelectInTarget: class com.intellij.ide.impl.ProjectPaneSelectInTarget
created by project pane:class com.igormaznitsa.ideamindmap.view.KnowledgeViewPane
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.addProjectPane(ProjectViewImpl.java:325)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.ensurePanesLoaded(ProjectViewImpl.java:538)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:506)
    at com.intellij.ide.projectView.impl.ProjectViewImpl.setupImpl(ProjectViewImpl.java:485)
    at com.intellij.ide.projectView.impl.ProjectViewToolWindowFactory.createToolWindowContent(ProjectViewToolWindowFactory.java:21)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:533)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.lambda$initToolWindow$9(ToolWindowManagerImpl.java:482)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindow(ToolWindowManagerImpl.java:485)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$5.run(ToolWindowManagerImpl.java:437)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
    at com.intellij.openapi.wm.impl.ToolWindowsPane$AddToolStripeButtonCmd.run(ToolWindowsPane.java:970)
    at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
    at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
    at com.intellij.openapi.wm.impl.CommandProcessor.flush(CommandProcessor.java:32)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.flushCommands(ToolWindowManagerImpl.java:568)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$3100(ToolWindowManagerImpl.java:70)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$InitToolWindowsActivity.lambda$runActivity$0(ToolWindowManagerImpl.java:2273)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:723)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:672)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:780)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:196)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:454)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:251)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:205)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:446)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:421)
    at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:260)
    at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:509)
    at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:628)
    at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:684)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
    at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
    at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
    at com.sun.proxy.$Proxy47.appStarting(Unknown Source)
    at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:370)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
    at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:368)
    at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:211)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:211)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by raydac** [comment]
as I see you work for JetBrains, may be you could provide some expertise how to be with the issue? it works well with Idea 2018 but may be Intellij team made some changes in API, is there any info?
[the class which throws error](https://github.com/raydac/netbeans-mmd-plugin/blob/master/mind-map/idea-mindmap/src/com/igormaznitsa/ideamindmap/view/KnowledgeViewPane.java)

**Comment by raydac** [comment]
I made some refactoring and the issue looks gone
