### ISSUE TITLE
IDEA Mind Map 1.4.10 + PhpStorm #PS-211.6432.17, built on March 12, 2021 Crash

### ISSUE THREAD

**Issue by desirepl** [raydac/netbeans-mmd-plugin#81]
PhpStorm 2021.1 Beta
Build #PS-211.6432.17, built on March 12, 2021
PhpStorm EAP User
Expiration date: April 11, 2021
Runtime version: 11.0.10+9-b1341.19 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry: run.processes.with.pty=TRUE, ide.completion.show.live.templates.on.top=true, ide.tooltip.initialDelay=600
Non-Bundled Plugins: BrowseWordAtCaret (3.0.4), CVS (203), FavoriteFolders (1.3.2), GrepConsole (11.6.211.6085.0), Key Promoter X (2021.1.1), Quick Notes (3.3), String Manipulation (8.13.203.000.0), awesome.console (0.1337.11), com.alayouni.ansiHighlight (1.2.4), com.intellij.ideolog (203.0.26.0), com.ivanovych666.intellij.plugin.jsonsorter (1.0.0-beta.3.4), com.karateca.jstoolbox (1.10), com.mnr.java.intellij.idea.plugin.base64helper (2.0.3), com.wix.scss.lint (2.1.1), indent-rainbow.indent-rainbow (1.6.1), krasa.CpuUsageIndicator (1.14), nb-mind-map-idea (1.4.10), net.vektah.codeglance (1.5.4), org.intellij.RegexpTester (1.0.8), com.intellij.plugins.html.instantEditing (211.6432.7), spy-js (211.6432.9), Karma (211.6432.7), com.dmarcotte.handlebars (211.6432.7), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.1), de.espend.idea.php.annotation (8.0.0), net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0), fr.adrienbrault.idea.symfony2plugin (0.22.206)

`Do not request resource from classloader using path with leading slash

com.intellij.diagnostic.PluginException: /i18n/Bundle.properties [Plugin: nb-mind-map-idea]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:410)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:376)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3218)
	at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
	at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at com.igormaznitsa.ideamindmap.plugins.PrinterPlugin.<clinit>(PrinterPlugin.java:24)
	at com.igormaznitsa.ideamindmap.settings.MindMapApplicationSettings.initComponent(MindMapApplicationSettings.java:57)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:57)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:340)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:342)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:198)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:419)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by raydac** [comment]
pls try snapshot https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.4.11-S

**Comment by desirepl** [comment]
Just installed it and not even tried when got a crash.
1.4.11-S loaded successfully.
