### ISSUE TITLE
Context menu keypress opens the context menu for root node rather than selected nodes

### ISSUE THREAD

**Issue by bonzaiferroni** [raydac/netbeans-mmd-plugin#90]
As stated in the title, a context menu key press 1) selects the root node (losing your selection) and 2) opens the context menu for the root node. This gif shows the behavior:

![rider64_2022-01-10_07-22-52](https://user-images.githubusercontent.com/10502552/148781979-c8bdb9c5-14ac-495b-91c0-6b8af36a7935.gif)

**Comment by raydac** [comment]
which version of application, is it a plugin or standalone application? which OS? what do you mean as context menu key?

**Comment by bonzaiferroni** [comment]
Sorry, should have mentioned. I'm using the Rider plugin. I'm on Windows. The context menu key exists on most keyboards and tends to be functionally equivalent to a right mouse button press:

https://en.wikipedia.org/wiki/Menu_key

**Comment by raydac** [comment]
ok, it's a bug, thanks a lot!

**Comment by raydac** [comment]
you can try [snapshot version](https://github.com/raydac/netbeans-mmd-plugin/releases/tag/1.5.1-S)

**Comment by bonzaiferroni** [comment]
Awesome! Looking forward to the next release.

This particular snapshot crashes for me:
![rider64_2022-01-14_10-36-22](https://user-images.githubusercontent.com/10502552/149560424-c1ec4f44-312c-4009-866d-0c0e90651c3c.png)

**Comment by krasa** [comment]
@bonzaiferroni you need to install the whole zip file

**Comment by krasa** [comment]
from this snapshot:
```
java.lang.AssertionError: Object must not be NULL
	at com.igormaznitsa.meta.common.utils.Assertions.assertNotNull(Assertions.java:125)
	at com.igormaznitsa.meta.common.utils.Assertions.assertNotNull(Assertions.java:108)
	at com.igormaznitsa.mindmap.swing.panel.utils.Pair.<init>(Pair.java:36)
	at com.igormaznitsa.mindmap.swing.panel.MindMapPanel.findBestPointForContextMenu(MindMapPanel.java:1306)
	at com.igormaznitsa.ideamindmap.editor.MindMapDocumentEditor.getData(MindMapDocumentEditor.java:943)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProvider(DataManagerImpl.java:71)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.doPreGetAllData(PreCachedDataContext2.java:255)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.preGetAllData(PreCachedDataContext2.java:229)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext2.<init>(PreCachedDataContext2.java:96)
	at com.intellij.openapi.actionSystem.impl.Utils.newPreCachedDataContext(Utils.java:83)
	at com.intellij.openapi.actionSystem.impl.Utils.wrapToAsyncDataContext(Utils.java:71)
	at com.intellij.openapi.actionSystem.impl.Utils.wrapDataContext(Utils.java:89)
	at com.intellij.ide.navigationToolbar.NavBarModel.wrapDataContext(NavBarModel.java:116)
	at com.intellij.ide.navigationToolbar.NavBarModel.updateModelAsync(NavBarModel.java:104)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue.requestModelUpdateFromContextOrObject(NavBarUpdateQueue.java:86)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$1.lambda$run$0(NavBarUpdateQueue.java:58)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.ide.navigationToolbar.NavBarUpdateQueue$1.run(NavBarUpdateQueue.java:57)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:147)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2196)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:241)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:374)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
